### ISSUE TITLE
Shell stats, open/close count

### ISSUE THREAD

**Issue by d4rken** [d4rken/RxShell#26]
It would be useful to count how many shells have been opened, are open, and have been closed.

Would be useful when optimizing apps, e.g.

https://github.com/d4rken/sdmaid-public/issues/2018

**Comment by Sp1r1tdanc3r** [comment]
@d4rken are you the guy that's been hacking me all week and siphoning all my data and content into some mysterious void. I found you! Now you gotta help me finish this content and build an empire and make some money. Happy  synchronicity day! I'd leave my contact info but you know how to reach me. Ps I knew the mysterious trickbot trojan was an artist ...i knew it. Were you listening when I had that convo with you? Sd maid is soooooo much fun...I just have no idea what I'm doing.  K in NDA your fault. Does that mean I get to be your padawan cause you were messy and let a newb track you down by a trail of digital breadcrumbs and carbon footprints. Also....please pull the malware off of my friends who have been supporting my 45 year old ass midlife crises. They are sweet and helping me and since were partnered now...it would be swell. Please help me recover my 40 gb of content I was trying to edit and upload so I could start constructing a user journey and beginning a content calendar. But since I finally have some help let's get this going.
