### ISSUE TITLE
Detect magisk hide

### ISSUE THREAD

**Issue by comomind** [d4rken/RxShell#27]
I tested Root Validator in nexus6 with magisk. Normally it works. Thanks! 👍 
But if magisk hide enabled (with magisk manager hiding enabled), 
RxShell rooting detection doesn't works.

**Comment by d4rken** [comment]
Isn't that working as intended though? Magisk hides root, if root could still be detected, then Magisk hide wouldn't be working?

**Comment by comomind** [comment]
yeah you were right in a view point of a magisk. 
But to be clear, one of the purpose of the rxshell is detecting root even though there are hiding schemes work or not, right? 
So I think rxshell rooting detection failed when magisk hide enabled is a false negative case.

**Comment by d4rken** [comment]
> But to be clear, one of the purpose of the rxshell is detecting root even though there are hiding schemes work or not, right?

No, it's purpose is for developers to check for root access in a friendly environment. If the user has decided to hide root from an app using RxShell, then it's not RxShell's purpose to try and circumvent that.

I like using root, I wouldn't want to build something that circumvents magisk hide as that would give other apps the chance to stop working on my device just because I have root.

**Comment by comomind** [comment]
I've misunderstood the purpose of rxshell. 
Thanks to your prompt reply. 👍
